spring:
  application:
    name: player-sheets-service
  datasource:
    url: jdbc:postgresql://localhost:5432/progetto_medusa
    username: admin
    password: admin123
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084

logging:
  level:
    root: INFO
    com:
      progettomedusa: DEBUG

security:
  licensed-apps:
    - local-postman
    - app2
    - app3