CREATE TABLE if not EXISTS player_sheets (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    race VARCHAR(50) NOT NULL,
    character_class VARCHAR(50) NOT NULL,
    background TEXT  NOT NULL,
    experience INTEGER DEFAULT 0  NOT NULL,
    level INTEGER DEFAULT 1  NOT NULL,
    alignment VARCHAR(30),

    strength INTEGER NOT NULL default(0),
    dexterity INTEGER NOT NULL default(0),
    constitution INTEGER NOT NULL default(0),
    intelligence INTEGER NOT NULL default(0),
    wisdom INTEGER NOT NULL default(0),
    charisma INTEGER NOT NULL default(0),
    
    armor_class INTEGER,
    speed INTEGER NOT NULL,
    initiative INTEGER NOT NULL,
    max_hit_points INTEGER NOT NULL,
    current_hit_points INTEGER,
    temp_hit_points INTEGER,
    hit_dice VARCHAR(20) NOT NULL,
    armor VARCHAR(100),
    weapons VARCHAR(100),
    tools VARCHAR(100),
    languages VARCHAR(100),
    
    acrobatics INTEGER NOT NULL default(0),
    animal_handling INTEGER NOT NULL default(0),
    arcana INTEGER NOT NULL default(0),
    athletics INTEGER NOT NULL default(0),
    deception INTEGER NOT NULL default(0),
    history INTEGER NOT NULL default(0),
    insight INTEGER NOT NULL default(0),
    intimidation INTEGER NOT NULL default(0),
    investigation INTEGER NOT NULL default(0),
    medicine INTEGER NOT NULL default(0),
    nature INTEGER NOT NULL default(0),
    perception INTEGER NOT NULL default(0),
    performance INTEGER NOT NULL default(0),
    persuasion INTEGER NOT NULL default(0),
    religion INTEGER NOT NULL default(0),
    sight_of_hand INTEGER NOT NULL default(0),
    stealth INTEGER NOT NULL default(0),
    survival INTEGER NOT NULL default(0),
    
    inspiration INTEGER NOT NULL default(0),
    proficiency_bonus INTEGER NOT NULL default(0),
    passive_perception INTEGER NOT NULL default(0),
    
    equipment1 VARCHAR(100),
    equipment2 VARCHAR(100),
    equipment3 VARCHAR(100),
    equipment4 VARCHAR(100),
    equipment5 VARCHAR(100),
    
    copper_currency INTEGER,
    bronze_currency INTEGER,
    silver_currency INTEGER,
    gold_currency INTEGER,
    platinum_currency INTEGER,
    
    attack1_name VARCHAR(50),
    attack1_bonus VARCHAR(20),
    attack1_damage VARCHAR(50),
    attack2_name VARCHAR(50),
    attack2_bonus VARCHAR(20),
    attack2_damage VARCHAR(50),
    attack3_name VARCHAR(50),
    attack3_bonus VARCHAR(20),
    attack3_damage VARCHAR(50), 

    saving_throw1 BOOLEAN DEFAULT FALSE NOT NULL,
    saving_throw2 BOOLEAN DEFAULT FALSE NOT NULL,
    saving_throw3 BOOLEAN DEFAULT FALSE NOT NULL,

    spellcasting_class VARCHAR(50),
    spellcasting_ability VARCHAR(50),
    spell_save_dc INTEGER,
    spell_attack_bonus INTEGER,

    cantrip1 VARCHAR(50),
    cantrip2 VARCHAR(50),
    cantrip3 VARCHAR(50),
    cantrip4 VARCHAR(50),
    
    spell_slots1 INTEGER,  spell_slots1_used BOOLEAN DEFAULT FALSE,
    spell_slots2 INTEGER,  spell_slots2_used BOOLEAN DEFAULT FALSE,
    spell_slots3 INTEGER,  spell_slots3_used BOOLEAN DEFAULT FALSE,
    spell_slots4 INTEGER,  spell_slots4_used BOOLEAN DEFAULT FALSE,
    spell_slots5 INTEGER,  spell_slots5_used BOOLEAN DEFAULT FALSE,
    spell_slots6 INTEGER,  spell_slots6_used BOOLEAN DEFAULT FALSE,
    spell_slots7 INTEGER,  spell_slots7_used BOOLEAN DEFAULT FALSE,
    spell_slots8 INTEGER,  spell_slots8_used BOOLEAN DEFAULT FALSE,
    spell_slots9 INTEGER,  spell_slots9_used BOOLEAN DEFAULT FALSE,
    
    personality_traits TEXT,
    ideals TEXT,
    bonds TEXT,
    flaws TEXT,
    feature1 TEXT,
    feature2 TEXT,
    feature3 TEXT,
    notes TEXT,
    backstory TEXT 
);

CREATE TABLE "user" (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  application_id VARCHAR(30),
  update_date VARCHAR(100) NOT NULL,
  insert_date VARCHAR(30) NOT NULL,
  is_valid BOOLEAN NOT NULL
);


INSERT INTO player_sheets (
    name, race, character_class, background, experience, level, alignment,
    strength, dexterity, constitution, intelligence, wisdom, charisma,
    armor_class, speed, initiative,
    max_hit_points, current_hit_points, hit_dice,
    weapons, tools, languages,
    proficiency_bonus, passive_perception,
    attack1_name, attack1_bonus, attack1_damage,
    attack2_name, attack2_bonus, attack2_damage,
    cantrip1, cantrip2
) VALUES (
    'Thalia Swiftfoot', 'Halfling', 'Rogue', 'Criminal', 2700, 3, 'Chaotic Neutral',
    8, 16, 14, 12, 13, 10,
    14, 25, 3,
    24, 24, '1d8',
    'Rapier, Shortbow', 'Thieves'' tools', 'Common, Halfling',
    2, 13,
    'Rapier', '+5', '1d8+3',
    'Shortbow', '+5', '1d6+3',
    'Minor Illusion', 'Mage Hand'
);


INSERT INTO player_sheets (
    name, race, character_class, background, experience, level, alignment,
    strength, dexterity, constitution, intelligence, wisdom, charisma,
    armor_class, speed, initiative,
    max_hit_points, current_hit_points, hit_dice,
    weapons, tools, languages,
    proficiency_bonus, passive_perception,
    attack1_name, attack1_bonus, attack1_damage,
    cantrip1, cantrip2,
    spellcasting_class, spellcasting_ability, spell_save_dc, spell_attack_bonus,
    spell_slots1, spell_slots1_used, spell_slots2, spell_slots2_used
) VALUES (
    'Dorian Firebrand', 'Tiefling', 'Warlock', 'Noble', 15000, 5, 'Neutral Good',
    10, 14, 12, 13, 12, 18,
    13, 30, 2,
    30, 30, '1d8',
    'Light crossbow, Dagger', NULL, 'Common, Infernal',
    3, 12,
    'Dagger', '+4', '1d4+2',
    'Eldritch Blast', 'Prestidigitation',
    'Warlock', 'CHA', 14, 6,
    2, FALSE, 2, FALSE
);

INSERT INTO player_sheets (
    name, race, character_class, background, experience, level, alignment,
    strength, dexterity, constitution, intelligence, wisdom, charisma,
    armor_class, speed, initiative,
    max_hit_points, current_hit_points, temp_hit_points, hit_dice,
    armor, weapons, tools, languages,
    acrobatics, animal_handling, arcana, athletics, deception, history, insight,
    intimidation, investigation, medicine, nature, perception, performance,
    persuasion, religion, sight_of_hand, stealth, survival,
    inspiration, proficiency_bonus, passive_perception,
    equipment1, equipment2, equipment3, equipment4, equipment5,
    copper_currency, bronze_currency, silver_currency, gold_currency, platinum_currency,
    attack1_name, attack1_bonus, attack1_damage,
    attack2_name, attack2_bonus, attack2_damage,
    attack3_name, attack3_bonus, attack3_damage,
    saving_throw1, saving_throw2, saving_throw3,
    spellcasting_class, spellcasting_ability, spell_save_dc, spell_attack_bonus,
    cantrip1, cantrip2, cantrip3, cantrip4,
    spell_slots1, spell_slots1_used, spell_slots2, spell_slots2_used,
    spell_slots3, spell_slots3_used, spell_slots4, spell_slots4_used,
    spell_slots5, spell_slots5_used, spell_slots6, spell_slots6_used,
    spell_slots7, spell_slots7_used, spell_slots8, spell_slots8_used,
    spell_slots9, spell_slots9_used,
    personality_traits, ideals, bonds, flaws,
    feature1, feature2, feature3, notes, backstory
) VALUES (
    'Ezio Auditore', 'Human', 'Assassin', 'Noble', 8500, 8, 'Chaotic Good',
    12, 18, 14, 13, 16, 14,
    16, 30, 4,
    60, 60, 0, '1d8',
    'Leather Armor, Hidden Blade',
    'Hidden Blade, Short Sword, Throwing Knives',
    'Thieves'' tools, Disguise kit',
    'Common, Italian',
    7, 3, 1, 1, 5, 1, 6, 2, 1, 3, 1, 3, 2, 2, 1, 7, 7, 3,
    1, 3, 15,
    'Hidden Blade', 'Smoke Bomb', 'Grappling Hook', 'Throwing Knives', 'Hooded Cloak',
    50, 10, 25, 100, 5,
    'Hidden Blade', '+7', '1d4+4',
    'Short Sword', '+7', '1d6+4',
    'Throwing Knife', '+7', '1d4+4',
    TRUE, TRUE, FALSE,
    '', '', 0, 0,
    '', '', '', '',
    0, FALSE, 0, FALSE, 0, FALSE, 0, FALSE, 0, FALSE, 0, FALSE, 0, FALSE, 0, FALSE, 0, FALSE,
    'Stoic, calculating, protective',
    'Freedom and justice above all',
    'Family and the Brotherhood',
    'Haunted by vengeance',
    'Eagle Vision',
    'Master of stealth',
    'Keen assassin instincts',
    'Master assassin from the Italian Brotherhood.',
    'Born in Florence to a noble family, Ezio became an orphan and rose through the ranks of the Assassin Brotherhood, fighting tyranny across Italy.'
);
